name: Build Rspack Binding

on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: 'Rspack repository to use'
        default: 'web-infra-dev/rspack'
      ref:
        type: string
        description: 'The branch, tag or SHA to checkout'

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  main:
    needs: [get-runner-labels]
    runs-on: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - name: Checkout Rspack repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      - name: Build Rspack
        run: |
          pnpm i --frozen-lockfile
          pnpm run build:binding:release
      - uses: actions/upload-artifact@v4
        with:
          name: binding-linux-x64-gnu
          path: crates/node_binding/*.node
