name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  prepare-binding:
    name: Prepare Rspack Binding
    needs: get-runner-labels
    runs-on: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-rspack-binding

  ci:
    needs: [get-runner-labels, prepare-binding]
    runs-on: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
    strategy:
      matrix:
        suite:
          - _selftest
          - modernjs
          - nx
          - rspress
          - rsbuild
          - compat
          - examples
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rspack
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        continue-on-error: true
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Format
        run: pnpm format
      - name: Lint
        run: pnpm lint
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          ${{ matrix.suite }}
