name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-binding:
    name: Build Rspack Binding
    uses: ./.github/workflows/build-rspack-binding.yaml

  ci:
    needs: build-binding
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - _selftest
          - modernjs
          - nx
          - rspress
          - rsbuild
          - compat
          - examples
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        continue-on-error: true

      - name: Checkout Rspack repo
        uses: actions/checkout@v4
        with:
          repository: web-infra-dev/rspack
          path: workspace/rspack
      - uses: actions/download-artifact@v4
        with:
          name: binding-linux-x64-gnu
          path: workspace/rspack/crates/node_binding
      - name: Show restored binding
        shell: bash
        run: ls -lah workspace/rspack/crates/node_binding/*.node
      - run: |
          cd workspace/rspack
          pnpm i
          pnpm run build:js

      - run: pnpm i
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --repo ${{ inputs.repo }}
          ${{ matrix.suite }}
