name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  prepare-binding:
    name: Prepare Rspack Binding
    needs: get-runner-labels
    runs-on: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-rspack-binding

  ci:
    needs: [get-runner-labels, prepare-binding]
    strategy:
      matrix:
        include:
          - suite: modernjs
            os: ubuntu-22.04
          - suite: _selftest
            os: ubuntu-22.04
          # - suite: nx
          #   os: ubuntu-22.04
          - suite: rspress
            os: ubuntu-22.04
          - suite: rsbuild
            os: ubuntu-22.04
          - suite: examples
            os: ubuntu-22.04
          - suite: rslib
            os: ubuntu-22.04
          - suite: rsdoctor
            os: ubuntu-22.04
          - suite: devserver
            os: ubuntu-22.04
          - suite: nuxt
            os: ubuntu-22.04
          - suite: plugin
            os: ubuntu-22.04
          - suite: nextjs
            os: ubuntu-22.04
            shard: [1/7, 2/7, 3/7, 4/7, 5/7, 6/7, 7/7]
          - suite: lynx-stack
            os: ubuntu-22.04
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rspack
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Format
        if: matrix.suite == '_selftest'
        run: pnpm format
      - name: Lint
        if: matrix.suite == '_selftest'
        run: pnpm lint
      - name: Setup Node.js
        if: matrix.suite == 'lynx-stack' || matrix.suite == '_selftest'
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Rust
        if: matrix.suite == 'lynx-stack'
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --shard ${{ matrix.shard }}
          ${{ matrix.suite }}
