name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  prepare-binding:
    name: Prepare Rspack Binding
    needs: get-runner-labels
    runs-on: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-rspack-binding

  ci:
    needs: [get-runner-labels, prepare-binding]
    strategy:
      matrix:
        include:
          - suite: modernjs
            os: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
          - suite: _selftest
            os: ubuntu-latest
          - suite: nx
            os: ubuntu-latest
          - suite: rspress
            os: ubuntu-latest
          - suite: rsbuild
            os: ubuntu-latest
          - suite: compat
            os: ubuntu-latest
          - suite: examples
            os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rspack
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Format
        run: pnpm format
      - name: Lint
        run: pnpm lint
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          ${{ matrix.suite }}
