name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  ci:
    needs: [get-runner-labels]
    runs-on: ${{ fromJSON(needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - name: install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: format
        run: pnpm format
      - name: lint
        run: pnpm run lint
      # - name: audit
      #   if: (${{ success() }} || ${{ failure() }})
      #   run: pnpm audit
      - name: test
        if: (${{ success() }} || ${{ failure() }})
        run: pnpm test:self
