# integration tests for rspack ecosystem projects - scheduled or manual run for all suites
name: rspack-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  schedule:
    # 10:00 AM Beijing Time, every day.
    - cron: "0 2 * * 0,1,2,3,4,5,6"
  workflow_dispatch:
    inputs:
      refType:
        description: "type of ref"
        required: true
        type: choice
        options:
          - branch
          - tag
          - commit
          - release
        default: "branch"
      ref:
        description: "rspack ref to use"
        required: true
        type: string
        default: "main"
      repo:
        description: "rspack repository to use"
        required: true
        type: string
        default: "web-infra-dev/rspack"
  repository_dispatch:
    types: [ecosystem-ci]
jobs:
  test-ecosystem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - modernjs
          - nx
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        id: setup-node
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        id: setup-deno
        continue-on-error: true
      - run: corepack enable
      - run: pnpm --version
      - run: pnpm i --frozen-lockfile
      - run: >-
          pnpm tsx ecosystem-ci.ts
          --${{ inputs.refType || github.event.client_payload.refType || 'release' }} ${{ inputs.ref || github.event.client_payload.ref || 'nightly' }}
          --repo ${{ inputs.repo || github.event.client_payload.repo || 'web-infra-dev/rspack' }}
          ${{ matrix.suite }}
        id: ecosystem-ci-run
      - if: always()
        run: pnpm tsx discord-webhook.ts
        env:
          WORKFLOW_NAME: ci
          REF_TYPE: ${{ inputs.refType || github.event.client_payload.refType || 'release' }}
          REF: ${{ inputs.ref || github.event.client_payload.ref || 'nightly' }}
          REPO: ${{ inputs.repo || github.event.client_payload.repo || 'web-infra-dev/rspack' }}
          SUITE: ${{ matrix.suite }}
          STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
